title: UCCU小站
description: UCCU的廢話區
theme: minima
baseurl: "urgangur.github.io/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - category
    title: ':cat'
    permalink: '/categories/:cat/'
    
pagination:
  enabled: true
  per_page: 10
  sort_field: 'date'
  sort_reverse: true

