title: UCCU小站
description: UCCU的廢話區
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate-v2

jekyll-archives:
  enabled:
    - categories
  layout: category
  permalinks:
    category: /categories/:name/
  paginatation:
    enabled: true
    per_page: 10
    permalinks: /categories/:name/page/:num/
