title: UCCU小站
description: UCCU的廢話區
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate-v2

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /categories/:name/

pagnination:
  enabled: true
  per_page: 10
  permalinks: /categories/:name/:num/
  trail:
    before: 2
    after: 2